Repository openebs/openebs, pull requests merged in 2019-03, with the labels that each got.

#2421 fix(0.7 to 0.8 upgrade): add version label to 0.7-0.8 upgrade.sh
  k8s/upgrades/0.7.0-0.8.0/cstor-pool-patch.tpl.json
  k8s/upgrades/0.7.0-0.8.0/cstor-target-patch.tpl.json
  k8s/upgrades/0.7.0-0.8.0/cstor-target-svc-patch.json
  k8s/upgrades/0.7.0-0.8.0/jiva-replica-patch.tpl.json
  k8s/upgrades/0.7.0-0.8.0/jiva-target-patch.tpl.json
  k8s/upgrades/0.7.0-0.8.0/jiva-target-svc-patch.json
  k8s/upgrades/0.7.0-0.8.0/jiva_volume_update.sh
  k8s/upgrades/0.8.0-0.8.1/README.md
  k8s/upgrades/0.8.0-0.8.1/cstor_pool_upgrade.sh
  k8s/upgrades/0.8.0-0.8.1/labeltagger.sh
  k8s/upgrades/0.8.0-0.8.1/pre-check.sh
Labels: review

#2423 refactor(readme): updates readme for 0.8.0-0.8.1 update scripts
  k8s/upgrades/0.8.0-0.8.1/README.md
Labels: review

#2426 fix(doc): updates wrong number of steps in upgrade script
  k8s/upgrades/0.8.0-0.8.1/README.md
Labels: review

#2428 fix(doc): fixes helm command for updating the openebs from 0.7.x-0.8.0
  k8s/upgrades/0.7.0-0.8.0/README.md
Labels: area/install/helm, review

#2439 feat(upgrade): add upgrade patch template for pool-exporter
  k8s/upgrades/0.8.1-0.8.2/cstor-pool-patch.tpl.json
Labels: area/upgrade, review

#2444 refactor(operator): change ndm tag to v0.3.2
  k8s/openebs-operator.yaml
Labels: review

#2430 fix(doc): fixes Update mount path of minio deployment
  k8s/demo/minio/minio.yaml
Labels: review

#2446 Fix(Doc) Replace slack sign up link by join our community page link
  CONTRIBUTING.md
  README.md
  community/README.md
  contribute/CONTRIBUTING-TO-CI-AND-E2E.md
  translations/CONTRIBUTING.tr.md
  translations/README.de.md
  translations/README.ru.md
  translations/README.tr.md
Labels: review

#2448 Included a task to check openebs admission server status
  e2e/ansible/roles/k8s-openebs-operator/tasks/main.yml
Labels: review

#2449 Modified deploy openebs ansible playbook
  e2e/ansible/roles/k8s-openebs-operator/tasks/main.yml
Labels: review

#2450 fix(readme): update install instructions to use helm
  README.md
  translations/README.de.md
  translations/README.ru.md
  translations/README.tr.md
Labels: review

#2452 Modified a task to fetch resource version of controller and replica in ansible playbooks
  e2e/ansible/playbooks/resiliency/test-ctrl-failure/test-ctrl-failure.yml
  e2e/ansible/playbooks/resiliency/test-replica-quorum-failure/inject_replica_quorum_failure.yml
  e2e/ansible/playbooks/resiliency/test-single-replica-failure/test-single-replica-failure.yml
Labels: review

#2458 feat(operator): add addmission server config yamls to 0.8.2
  k8s/openebs-operator.yaml
Labels: review

#2460 Refact(operator): add clusterRole permission for csp subresources
  k8s/openebs-operator.yaml
Labels: review

#2457 feat(upgrade): upgrade openebs volume and pools to 0.8.2
  k8s/upgrades/0.8.1-0.8.2/README.md
  k8s/upgrades/0.8.1-0.8.2/cr-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor-target-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor-target-svc-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor-volume-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor-volume-replica-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor_pool_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/cstor_volume_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/jiva-replica-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/jiva-target-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/jiva-target-svc-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/jiva_volume_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/labeltagger.sh
  k8s/upgrades/0.8.1-0.8.2/pre-check.sh
Labels: area/upgrade, review

#2462 refact(operator): operator yaml to validate the volume CREATE request
  k8s/openebs-operator.yaml
Labels: review

#2461 feat(upgrade snapshotdata)patch volumesnapshotdata crs as a part of volume upgrades
  k8s/upgrades/0.8.1-0.8.2/cstor_volume_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/jiva_volume_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/snapshotdata_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/volumesnapshotdata-patch.tpl.json
Labels: review

#2463 [cherry-pick] Refact(operator): refactor the operator yaml which will validates the clone creation
  k8s/openebs-operator.yaml
Labels: review

#2466 fix(upgrade): remove custom label input in 0.6 upgrade
  k8s/upgrades/0.6.0-0.7.0/oebs_update.sh
  k8s/upgrades/0.7.0-0.8.0/jiva_volume_update.sh
Labels: review

#2468 enhance(upgrade): Add upgrade script for upgrading jiva volumes from 0.6 to 0.8.1
  k8s/upgrades/jiva-0.6.0-0.8.1/README.md
  k8s/upgrades/jiva-0.6.0-0.8.1/jiva-replica-patch.tpl.json
  k8s/upgrades/jiva-0.6.0-0.8.1/jiva-target-patch.tpl.json
  k8s/upgrades/jiva-0.6.0-0.8.1/jiva-target-svc-patch.tpl.json
  k8s/upgrades/jiva-0.6.0-0.8.1/jiva_volume_upgrade.sh
  k8s/upgrades/jiva-0.6.0-0.8.1/patch-strategy-recreate.json
  k8s/upgrades/jiva-0.6.0-0.8.1/pre_upgrade.sh
  k8s/upgrades/jiva-0.6.0-0.8.1/replica-patch-remove-labels.json
  k8s/upgrades/jiva-0.6.0-0.8.1/sc.patch.tpl.yaml
  k8s/upgrades/jiva-0.6.0-0.8.1/target-patch-remove-labels.json
  k8s/upgrades/jiva-0.6.0-0.8.1/target-svc-patch-remove-labels.json
  k8s/upgrades/jiva-0.6.0-0.8.1/upgrade_sc.sh
Labels: review
