Repository openebs/openebs, pull requests merged in 2019-09, with the labels that each got.

#2595 oep:(cspc,csp,day2ops) propose schema changes for pool resources and workflow for day 2 ops
  contribute/design/1.x/cstor-operator/doc.md
Labels: type: OEP, type: Schema

#2732 refact(cspc-operator): added cspc crd yaml to cspc-operator
  k8s/cspc-operator.yaml
  k8s/cspc_install.sh
Labels: release-note

#2740 doc(governance): add initial draft on security policy
  SECURITY.md
Labels: area/security
