Repository openebs/openebs, pull requests merged in 2019-04, with the labels that each got.

#2481 chore(operator yaml): set default sparse pool creation to false
  k8s/openebs-operator.yaml
Labels: documentation, review

#2487 refactor[yaml]: Removed the task to check default cstor pool pods in ansible playbook
  e2e/ansible/roles/k8s-openebs-operator/tasks/main.yml
Labels: review

#2484 Refact(helm,upgrade): Update helm upgrade steps
  k8s/upgrades/0.7.0-0.8.0/README.md
  k8s/upgrades/0.8.0-0.8.1/README.md
  k8s/upgrades/dev/README.md
  k8s/upgrades/dev/cr-patch.tpl.json
  k8s/upgrades/dev/cstor-pool-patch.tpl.json
  k8s/upgrades/dev/cstor-target-patch.tpl.json
  k8s/upgrades/dev/cstor-target-svc-patch.tpl.json
  k8s/upgrades/dev/cstor-volume-patch.tpl.json
  k8s/upgrades/dev/cstor-volume-replica-patch.tpl.json
  k8s/upgrades/dev/cstor_pool_upgrade.sh
  k8s/upgrades/dev/cstor_volume_upgrade.sh
  k8s/upgrades/dev/jiva-replica-patch.tpl.json
  k8s/upgrades/dev/jiva-target-patch.tpl.json
  k8s/upgrades/dev/jiva-target-svc-patch.tpl.json
  k8s/upgrades/dev/jiva_volume_upgrade.sh
  k8s/upgrades/dev/labeltagger.sh
  k8s/upgrades/dev/pre-check.sh
  k8s/upgrades/dev/snapshotdata_upgrade.sh
  k8s/upgrades/dev/volumesnapshotdata-patch.tpl.json
Labels: review

#2494 fix(operator):Remove admission-server deployment and service for 0.8.2 release
  k8s/openebs-operator.yaml
Labels: review

#2496 Refactor[ansible]: Removed the task to check admission server status
  e2e/ansible/roles/k8s-openebs-operator/tasks/main.yml
Labels: review

#2501 feat(demo-app): Include demo mongodb statefulset(1r) yaml with target affinity
  k8s/demo/mongodb/demo-mongo-cstor-taa.yaml
Labels: review

#2513 doc(architecture): update architecture doc with 0.9
  contribute/design/README.md
Labels: review

#2490 chore(upgrade) upgrade script for 0.8.2 from 0.8.1
  k8s/upgrades/0.8.1-0.8.2/README.md
  k8s/upgrades/0.8.1-0.8.2/cr-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor-pool-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor-target-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor-target-svc-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor-volume-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor-volume-replica-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/cstor_pool_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/cstor_volume_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/jiva-replica-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/jiva-target-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/jiva-target-svc-patch.tpl.json
  k8s/upgrades/0.8.1-0.8.2/jiva_volume_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/labeltagger.sh
  k8s/upgrades/0.8.1-0.8.2/pre-check.sh
Labels: review

#2524 chore(ci script): update ci script to replace storagepool object operations with that of cstorpool
  k8s/ci/test-script.sh
Labels: review

#2526 fix(travis): Use cstorpool name instead of storagepool
  k8s/ci/test-script.sh
Labels: area/ci, review

#2528 Refact(operator): add clusterRole permission for spc subresources
  k8s/openebs-operator.yaml
Labels: review

#2533 chore(upgrade): change upgrade version from 0.8.2-RC4 to 0.8.2
  k8s/upgrades/0.8.1-0.8.2/README.md
  k8s/upgrades/0.8.1-0.8.2/cstor_pool_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/cstor_volume_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/jiva_volume_upgrade.sh
  k8s/upgrades/0.8.1-0.8.2/labeltagger.sh
Labels: review

#2517 feat(operator): adds the openebs.io/version label to the OpenEBS control plane pods
  k8s/openebs-operator.yaml
Labels: review
