Repository openebs/openebs, pull requests merged in 2020-10, with the labels that each got.

#3162 Add French translation
  README.md
  translations/CONTRIBUTING.fr.md
  translations/README.de.md
  translations/README.fr.md
  translations/README.ru.md
  translations/README.tr.md
  translations/README.ua.md
  translations/README.zh.md
  translations/TRANSLATIONS.md
Labels: Hacktoberfest

#3154 chore(docs):Update URLs and dead link
  community/README.md
  contribute/design/README.md
  contribute/git-commit-message.md
  k8s/vagrant/CentOS_Vagrant.md
Labels: Hacktoberfest, pr/missing-dco

#3172 DOCS: Add Gujarati language translations
  README.md
  translations/CONTRIBUTING.gu.md
  translations/README.de.md
  translations/README.fr.md
  translations/README.gu.md
  translations/README.md
  translations/README.ru.md
  translations/README.tr.md
  translations/README.ua.md
  translations/README.zh.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3205 [#3203] Translate documentation to Brazilian Portuguese
  README.md
  translations/CONTRIBUTING.pt-BR.md
  translations/README.pt-BR.md
Labels: Hacktoberfest, contributor-docs, docs, good first issue, hacktoberfest-accepted

#2840 oep(cstor): proposal to migrate pools and volumes from old schema to new schema
  contribute/design/1.x/migrate/spc-to-cspc-migration.md
Labels: no-pr-activity

#3232 Fixed Very Simple Typos in Roadmap.md
  ROADMAP.md
Labels: Hacktoberfest, docs

#3243 Update oep-template.md
  contribute/process/oep-template.md
Labels: Hacktoberfest, docs

#3165 Added Hindi translation
  CONTRIBUTING.md
  README.md
  translations/CONTRIBUTING.hi.md
  translations/README.hi.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3231 Added Arabic Language Translations
  translations/CONTRIBUTING.ar.md
  translations/README.ar.md
  translations/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3233 Translate documentation to Punjabi
  translations/CONTRIBUTING.pu.MD
  translations/README.md
  translations/README.pu.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3235 Fix grammatical errors in RELEASE.md
  RELEASE.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3242 Updated Expired URL | Removed Reference to Deleted Files
  k8s/demo/scripts/README.md
  k8s/openshift/byo/baremetal/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3229 Add Indonesia translations with my original translate.
  translations/CONTRIBUTING.id.md
  translations/README.id.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3225 Updated Docs
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3244 Translate documentation to Malayalam
  translations/CONTRIBUTING.mal.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3249 Updated Readme.md
  README.md
Labels: Hacktoberfest, pr/missing-dco

#3257 Updated README.de.md
  translations/README.de.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3268 feat: add link to pt-BR translation
  translations/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3270 New Readme translation file added, translation readme file update.
  translations/README.JP.md
  translations/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3271 Translate documentation to Spanish
  README.md
  translations/CODE_OF_CONDUCT.es.md
  translations/CONTRIBUTING.es.md
  translations/README.es.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3286 Updated README files
  k8s/demo/percona/README.md
  k8s/lib/vagrant/README.md
  k8s/upgrades/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3290 Added Nepali language
  translations/CONTRIBUTING.np.md
  translations/README.np.md
Labels: Hacktoberfest, hacktoberfest-accepted

#3278 Multiple fixes in the Turkish documentation
  translations/README.tr.md
Labels: Hacktoberfest, hacktoberfest-accepted
